package com.fournodes.ud.pranky;

public class GridItem {

    public String item; //Item NAME or LOCATION fetched from the database
    public int itemID; //Item position
    public int itemResID; //Item resource number generated by android fetched from database
    public int itemVolume; //Item volume fetched from database
    public int itemRepeatCount; //Item repeat value fetched from database

    // For non-sound item i.e VIBRATE, CAMERA FLASH etc
    public GridItem(int itemID, int itemResID, String item) {
        this.itemID = itemID;
        this.itemResID = itemResID;
        this.item = item;
    }
    // For sound playback items i.e all pre included sounds and custom sounds
    public GridItem(int itemID, int itemResID, String item, int itemRepeatCount, int itemVolume) {
        this.itemID = itemID;
        this.itemResID = itemResID;
        this.item = item;
        this.itemVolume = itemVolume;
        this.itemRepeatCount = itemRepeatCount;
    }
}
